export type LandingLang = "en" | "bn";

export const landingContent = {
  en: {
    hero: {
      eyebrow: "Good morning",
      headline: "A calmer day, with a companion who remembers.",
      sub: "Shathi listens, notices patterns in your mood, sleep, and habits, and gently nudges — never nags.",
      ctaPrimary: "Begin a quieter day",
      ctaSecondary: "See how a day unfolds",
      microproof: "Designed with care for South Asian rhythms.",
    },
    wake: {
      eyebrow: "Wake",
      headline: "How are you, really?",
      sub: "Two taps. Honest check-in. No streaks to protect. You can skip. You can lie. We'll still be here tomorrow.",
      cardTitle: "How are you feeling?",
      energy: "Energy",
      skip: "Skip today",
      save: "Save",
    },
    tend: {
      eyebrow: "Tend",
      headline: "Tiny, repeatable, skip-able.",
      sub: "Long-press any habit to skip with a reason. We count skips as data, not failure.",
      note: "No streaks to protect · No shame on misses.",
      habits: [
        { name: "Morning calm", done: 5, skipped: false },
        { name: "Hydration", done: 4, skipped: false },
        { name: "Evening journal", done: 2, skipped: true, skipReason: "low energy" },
      ],
    },
    reflect: {
      eyebrow: "Reflect",
      headline: "A page that waits.",
      sub: "Write a little. Or just a sentence. Auto-saved. Private by default. No likes, no comments.",
      prompt: "What's one thing that felt lighter today?",
      entry:
        "The walk after lunch helped. I didn't fix everything, but I noticed the air felt softer.",
      footer: "Private · Only you",
      chars: "182 chars",
      time: "Today, 8:30 PM",
      autosaved: "Auto-saved",
    },
    understand: {
      eyebrow: "Understand",
      headline: "Patterns, not judgments.",
      sub: "We surface what we notice. You decide what it means.",
      title: "This week, with you",
      chip: "Auto-generated · You can edit",
      insights: [
        { text: "Sleep was shortest on Sundays", meta: "3 of 7 nights" },
        { text: "You check in most on Wednesdays", meta: "Avg 8:42 AM" },
        { text: "Three calm mornings in a row", meta: "Trend up" },
      ],
      footer: "We surface what we notice. You decide what it means.",
      edit: "Edit this insight",
    },
    rest: {
      eyebrow: "Rest",
      headline: "Sleep is the real metric.",
      sub: "Log a wind-down time, not a score. We track consistency, not perfection.",
      lastNight: "Last night",
      logged: "Logged 7:18 AM",
      duration: "6h 42m",
      goal: "Goal 7h 30m · 12 min short",
      windDown: "Wind-down at 10:48 PM · 14 min to fall asleep.",
    },
    proof: {
      eyebrow: "After a week",
      headline: "What people notice",
      quotes: [
        "I stopped dreading Sundays.",
        "The journal is the part I open first now.",
        "I like that I can skip a habit and it doesn't guilt me.",
      ],
    },
    promise: {
      eyebrow: "Privacy by design",
      headline: "Private. Crisis-safe. Yours to leave.",
      lines: [
        "Your journal entries are end-to-end private. We don't sell data, ever.",
        "If you mention self-harm, Shathi pauses and surfaces Bangladesh and international crisis lines. We never auto-message them.",
        "You can export or delete everything from Settings → Privacy.",
      ],
      privacy: "Privacy policy",
      crisis: "Crisis resources",
      export: "Data export",
    },
    cta: {
      headline: "Begin a quieter day.",
      sub: "Free to start. No credit card. Cancel from settings.",
      primary: "Create my companion",
      secondary: "I already have an account →",
    },
    footer: {
      tagline: "Made with care in Dhaka",
      stayUpdated: "Stay updated",
      emailPlaceholder: "Enter your email",
      newsletterHint: "Weekly wellness notes, no spam.",
      copyright: "© 2026 Shathi.",
    },
  },
  bn: {
    hero: {
      eyebrow: "সুপ্রভাত",
      headline: "একটু শান্ত দিন, যে কিন্তু মনে রাখে আপনাকে।",
      sub: "শাথী শোনে, আপনার মেজাজ-ঘুম-অভ্যাসের ছন্দ বোঝে, আর আলতো করে বলে — কখনো জোর করে না।",
      ctaPrimary: "একটু শান্ত দিন শুরু করুন",
      ctaSecondary: "এক দিন কেমন যায় দেখুন",
      microproof: "দক্ষিণ এশিয়ার ছন্দের জন্য যত্নে তৈরি।",
    },
    wake: {
      eyebrow: "জাগরণ",
      headline: "আসলে কেমন লাগছে?",
      sub: "দুই টোকা। সত্যি করে বলুন। স্ট্রিক রক্ষার চাপ নেই। এড়িয়ে যান, মিথ্যা বলুন — আমরা কালও এখানে।",
      cardTitle: "আপনার মন কেমন?",
      energy: "শক্তি",
      skip: "আজ এড়িয়ে যান",
      save: "সংরক্ষণ",
    },
    tend: {
      eyebrow: "অভ্যাস",
      headline: "ছোট, পুনরাবৃত্তিযোগ্য, এড়ানোও যায়।",
      sub: "যেকোনো অভ্যাসে লং-প্রেস করে কারণ দিয়ে স্কিপ করুন। স্কিপও ডেটা, ব্যর্থতা নয়।",
      note: "স্ট্রিক রক্ষার চাপ নেই · মিস করলেও দোষ নেই",
      habits: [
        { name: "সকালের শান্তি", done: 5, skipped: false },
        { name: "পানি", done: 4, skipped: false },
        { name: "সন্ধ্যার জার্নাল", done: 2, skipped: true, skipReason: "কম শক্তি" },
      ],
    },
    reflect: {
      eyebrow: "প্রতিফলন",
      headline: "এক পাতা যা অপেক্ষা করে।",
      sub: "একটু লিখুন। একটা বাক্য দিয়েও শুরু হয়। অটো-সেভ। গোপন। লাইক নেই, কমেন্ট নেই।",
      prompt: "আজ কোন একটা জিনিস হালকা লাগল?",
      entry: "লাঞ্চের পর হাঁটা সাহায্য করেছে। সব ঠিক না, কিন্তু বাতাসটা নরম লাগল।",
      footer: "গোপন · শুধু আপনার",
      chars: "১৮২ অক্ষর",
      time: "আজ, ৮:৩০ PM",
      autosaved: "অটো-সেভ",
    },
    understand: {
      eyebrow: "বোঝা",
      headline: "ছন্দ, বিচার না।",
      sub: "আমরা যা দেখি, দেখাই। অর্থ আপনি ঠিক করেন।",
      title: "এই সপ্তাহ, আপনার সাথে",
      chip: "অটো-জেনারেট · সম্পাদনা করতে পারবেন",
      insights: [
        { text: "রবিবার ঘুম সবচেয়ে কম", meta: "৭ রাতের ৩" },
        { text: "বুধবার সবচেয়ে বেশি চেক-ইন", meta: "সাধারণ ৮:৪২ AM" },
        { text: "তিন শান্ত সকাল একসাথে", meta: "ছন্দ বাড়ছে" },
      ],
      footer: "আমরা যা দেখি, দেখাই। অর্থ আপনি ঠিক করেন।",
      edit: "ইনসাইট সম্পাদনা",
    },
    rest: {
      eyebrow: "বিশ্রাম",
      headline: "ঘুমই আসল হিসাব।",
      sub: "স্কোর না, বিশ্রামের সময় লগ করুন। নিয়মিততা, পারফেকশন নয়।",
      lastNight: "গত রাত",
      logged: "৭:১৮ AM লগ",
      duration: "৬ঘ ৪২মি",
      goal: "লক্ষ্য ৭ঘ ৩০মি · ১২ মিনিট কম",
      windDown: "বিশ্রাম ১০:৪৮ PM · ঘুমাতে ১৪ মিনিট।",
    },
    proof: {
      eyebrow: "এক সপ্তাহ পর",
      headline: "লোকেরা যা লক্ষ্য করেন",
      quotes: [
        "রবিবার নিয়ে আর ভয় লাগে না।",
        "আমি এখন আগে জার্নালটাই খুলি।",
        "অভ্যাস স্কিপ করলেও কোনো দোষ দেয় না — এটাই ভালো লাগে।",
      ],
    },
    promise: {
      eyebrow: "গোপনীয়তা নকশায়",
      headline: "গোপন। নিরাপদ। আপনার ছেড়ে যাওয়ার অধিকার।",
      lines: [
        "জার্নাল এন্ড-টু-এন্ড গোপন। ডেটা বিক্রি করি না, কখনোই।",
        "আত্মহত্যার ইঙ্গিতে শাথী থামে ও বাংলাদেশ ও আন্তর্জাতিক ক্রাইসিস লাইন দেখায়। আমরা কাউকে অটো-মেসেজ করি না।",
        "সেটিংস → গোপনীয়তা থেকে সব এক্সপোর্ট বা মুছে ফেলতে পারবেন।",
      ],
      privacy: "গোপনীয়তা নীতি",
      crisis: "ক্রাইসিস সংস্থান",
      export: "ডেটা এক্সপোর্ট",
    },
    cta: {
      headline: "একটু শান্ত দিন শুরু করুন।",
      sub: "বিনামূল্যে শুরু। কার্ড লাগবে না। সেটিংস থেকে বাতিল।",
      primary: "সাথী তৈরি করুন",
      secondary: "আমার অ্যাকাউন্ট আছে →",
    },
    footer: {
      tagline: "ঢাকায় যত্নে তৈরি",
      stayUpdated: "আপডেট পান",
      emailPlaceholder: "ইমেইল লিখুন",
      newsletterHint: "সাপ্তাহিক নোট, স্প্যাম নেই।",
      copyright: "© ২০২৬ শাথী।",
    },
  },
} as const;
